language: node_js
node_js:
  - 12

services:
  - docker

script:
  - yarn
  - yarn test
  - travis_wait 30 docker build -t berviantoleo/siwb .
  - docker run -d berviantoleo/siwb
  - sleep 60
  - docker ps -a